// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6QtnrUuReAozrmSHt5fGW4owrWIQkjMw',
    appId: '1:633086348523:web:1342a7f036db2c47f702ae',
    messagingSenderId: '633086348523',
    projectId: 'flutter-chat-app-4e33c',
    authDomain: 'flutter-chat-app-4e33c.firebaseapp.com',
    storageBucket: 'flutter-chat-app-4e33c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTXFmNmIUTV6fMxfk-W98q10sZWOJHlZM',
    appId: '1:633086348523:android:bf12bd84648cac6cf702ae',
    messagingSenderId: '633086348523',
    projectId: 'flutter-chat-app-4e33c',
    storageBucket: 'flutter-chat-app-4e33c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGuQsgTuhABV9FIT7sdL7kYhiOYEDLKFM',
    appId: '1:633086348523:ios:e12ce5280bba6eaff702ae',
    messagingSenderId: '633086348523',
    projectId: 'flutter-chat-app-4e33c',
    storageBucket: 'flutter-chat-app-4e33c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGuQsgTuhABV9FIT7sdL7kYhiOYEDLKFM',
    appId: '1:633086348523:ios:e12ce5280bba6eaff702ae',
    messagingSenderId: '633086348523',
    projectId: 'flutter-chat-app-4e33c',
    storageBucket: 'flutter-chat-app-4e33c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6QtnrUuReAozrmSHt5fGW4owrWIQkjMw',
    appId: '1:633086348523:web:8d3975d202d1aadff702ae',
    messagingSenderId: '633086348523',
    projectId: 'flutter-chat-app-4e33c',
    authDomain: 'flutter-chat-app-4e33c.firebaseapp.com',
    storageBucket: 'flutter-chat-app-4e33c.appspot.com',
  );
}
